### ISSUE TITLE
Relay problem

### ISSUE THREAD

**Issue by uok825** [CaptainDario/RPI-Zero-MagicMirror#1]
My relay is closing monitor but cant open it. Help me

**Comment by dariyooo** [comment]
What did you do until now?

**Comment by uok825** [comment]
> What did you do until now?

Yesterday just turn of but when i want to open it i need to first close then open it in the same python file.
But today my fucking relay is not opening or closing I was pissed off. Can you help me

**Comment by dariyooo** [comment]
So did you run the python script via command line and it is not closing/opening?

Did you choose the 2nd option?

**Comment by uok825** [comment]
> So did you run the python script via command line and it is not closing/opening?
> 
> Did you choose the 2nd option?

yes command line. I was prefer 2nd option but after update 2.12 mm it is not working anymore. so i build i python code but now my relay is not working. I think I went crazy

```
#!/usr/bin/env python
 
import sys
import time
import RPi.GPIO as io
import subprocess
 
io.setmode(io.BCM)
SHUTOFF_DELAY = 60  # seconds
PIR_PIN = 24
 
def main():
    io.setup(PIR_PIN, io.IN)
    turned_off = False
    last_motion_time = time.time()
 
    while True:
        if io.input(PIR_PIN):
            last_motion_time = time.time()
            sys.stdout.flush()
            if turned_off:
                turned_off = False
                turn_on()
        else:
            if not turned_off and time.time() > (last_motion_time + SHUTOFF_DELAY):
                turned_off = True
                turn_off()
        time.sleep(.1)
 
def turn_on():
   subprocess.call("sh monitor_on.sh", shell=True)
def turn_off():
   subprocess.call("sh monitor_off.sh", shell=True)
 
if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        io.cleanup()

```

**Comment by dariyooo** [comment]
If you just run [this script](https://github.com/CaptainDario/RPI-Zero-MagicMirror/blob/master/relay/turnOffRelay.py) the relay does not switch off ([This](https://github.com/CaptainDario/RPI-Zero-MagicMirror/blob/master/relay/turnOnRelay.py) to turn it on)?

**Comment by uok825** [comment]
> If you just run [this script](https://github.com/CaptainDario/RPI-Zero-MagicMirror/blob/master/relay/turnOffRelay.py) the relay does not switch off ([This](https://github.com/CaptainDario/RPI-Zero-MagicMirror/blob/master/relay/turnOnRelay.py) to turn it on)?

No it is not toggle relay.

**Comment by dariyooo** [comment]
Have you checked the connections?
All pins are correctly set and not loose?

**Comment by uok825** [comment]
> Have you checked the connections?
> All pins are correctly set and not loose?

I can't check cause i built the mirror and its hanging on a wall. I will check after dinner.

**Comment by dariyooo** [comment]
Seems to be solved.

Closing this.
